services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d authtest -U postgres"]
      timeout: 5s
      interval: 10s
      retries: 3
      start_period: 30s
    networks:
      - authtest
    volumes:
      - db_authtest:/var/lib/postgresql/data
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: avoiid/authtest:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${DB_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SECRET_TOKEN: ${SECRET_TOKEN}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - authtest
    volumes:
      - api_authtest:/var/lib/app

networks:
  authtest:
    driver: bridge

volumes:
  db_authtest:
  api_authtest: